=== mdbekkouche/LocFaults-IISs/core/xml/method.dtd
<!-- IDS d'une methode -->
<!-- ***************** -->

<!-- Tous les elements qui commencent par IDS sont dans l'IDS du projet java
     les modifications par rapport au projet java sont indiquees en commentaire -->


<!-- la syntaxe des expressions -->

<!-- les expressions entieres -->
<!-- j'ai enleve expr a la fin : IDSExprPlusEpr devient IDSExprPlus -->
<!ENTITY % ExprInt "(IDSExprIdent|IDSArrayExprIndex|LengthIdent|IDSExprPlus|IDSExprMinus|IDSExprTimes|IDSExprDecimalIntegerLiteral|IDSExprParenthesis|IDSExprJMLResult)">

<!ELEMENT IDSExprPlus (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprMinus (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprTimes (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprDiv (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprDecimalIntegerLiteral EMPTY>
<!ATTLIST IDSExprDecimalIntegerLiteral value CDATA #IMPLIED>
<!-- ******** -->

<!-- les expressions logiques -->
<!-- j'ai rajoute ExprLogical en racine de toutes les expressions logiques -->
<!-- j'ai enleve expr a la fin : IDSExprLogicalOrEpr devient IDSExprLogicalOr -->
<!ENTITY % ExprLogical "(IDSExprLogicalOr|IDSExprLogicalAnd|IDSExprLogicalNot|IDSExprParenthesis|IDSExprEquality|IDSExprSup|IDSExprInf|IDSExprJMLimplies|IDSJMLForAll|IDSJMLExist|IDSJMLAssert|IDSJMLAlldiff)">

<!ELEMENT IDSExprLogicalOr (%ExprLogical;,(%ExprLogical;)+)>
<!ELEMENT IDSExprLogicalAnd (%ExprLogical;,(%ExprLogical;)+)>
<!ELEMENT IDSExprLogicalNot (%ExprLogical;)>
<!ELEMENT IDSExprJMLimplies (%ExprLogical;,%ExprLogical;)>

<!-- couple d'expressions entieres pour les operations de comparaison -->
<!ENTITY % Compare "(%ExprInt;,%ExprInt;)">

<!-- operateurs de comparaison -->
<!ELEMENT IDSExprEquality (%Compare;)>
<!ELEMENT IDSExprSup (%Compare;)>
<!ELEMENT IDSExprInf (%Compare;)>
<!ELEMENT IDSExprSupEqual (%Compare;)>
<!ELEMENT IDSExprInfEqual (%Compare;)>

<!-- ******** -->

<!-- les parentheses -->
<!ELEMENT IDSExprParenthesis (%ExprLogical;|%ExprInt;)*>

<!-- **************************************************** -->
<!-- element racine : la methode -->

<!-- fichier a analyser -->
<!ELEMENT method (methodComment+,IDSMethod)>

<!ELEMENT methodComment (#PCDATA)>

<!-- signature, specification, program -->
<!ELEMENT IDSMethod (IDSSignature,IDSMethodSpecification,IDSJavaBloc)>

<!-- signature = parametres -->
<!ELEMENT IDSSignature (IDSParameter)>
<!ATTLIST IDSSignature returnType CDATA #IMPLIED
                    name CDATA #IMPLIED>


<!-- les parametres -->
<!ELEMENT IDSParameter (IDSExprIdent|IDSArrayExprIdent)>
<!ATTLIST IDSParameter type CDATA #IMPLIED>


<!-- la specification = requires optionnel et ensure obligatoire -->
<!ELEMENT IDSMethodSpecification (IDSRequiresClause+,IDSEnsuresClause)>

<!-- requires et ensures -->
<!ELEMENT IDSRequiresClause (%ExprLogical;)>
<!ELEMENT IDSEnsuresClause (%ExprLogical;)>

<!-- ASSERT -->
<!ELEMENT IDSJMLAssert (%ExprLogical;)>

<!-- ALLDIFF -->
<!ELEMENT IDSJMLAlldiff (IDSArrayExprIdent)>


<!-- le \result de la specification -->
<!-- dans jmlTT, IDSExprB_Result avec attribut name="" -->
<!ELEMENT IDSExprJMLResult EMPTY>


<!-- **************************************************** -->

<!-- un bloc java : declaration de variables, affectation, if, while -->
<!ENTITY % javaBloc "(IDSJavaDeclVarStatment*,(IDSJavaAssignmentStatment*|IDSJavaIfStatment*|IDSJavaWhileStatment*))">

<!-- le programme = un bloc java suivi eventuellement de return -->
<!ELEMENT IDSJavaBloc (%javaBloc;,IDSJavaReturnStatment?)>

<!-- variables simples -->

<!-- declaration -->
<!ELEMENT IDSJavaDeclVarStatment (%ExprInt;)>
<!ATTLIST IDSJavaDeclVarStatment name CDATA #IMPLIED>

<!-- les identificateurs -->
<!-- A CHANGER : name = nom dans projet SI2 -->
<!ELEMENT IDSExprIdent EMPTY>
<!ATTLIST IDSExprIdent name CDATA #IMPLIED> 

<!-- affectation -->
<!ELEMENT IDSJavaAssignmentStatment (%ExprInt;)+>
<!ATTLIST IDSJavaAssignmentStatment name CDATA #IMPLIED>

<!-- les tableaux -->


<!-- variable pour représenter la longueur du tableau -->
<!--  name  est le nom du tableau associé, -->
<!--  la longueur se trouve dans la var tableau elle-même  -->
<!ELEMENT LengthIdent EMPTY>
<!ATTLIST  LengthIdent
           name CDATA #IMPLIED>

<!-- declaration -->
<!ELEMENT IDSJavaDeclArrayStatment EMPTY>
<!ATTLIST IDSJavaDeclArrayStatment 
          length CDATA #IMPLIED
          name CDATA #IMPLIED>

<!-- les identificateurs -->
<!ELEMENT IDSArrayExprIdent EMPTY>
<!ATTLIST IDSArrayExprIdent 
           length CDATA #IMPLIED
           name CDATA #IMPLIED>

<!-- les valeurs  -->
<!ELEMENT IDSArrayExprIndex (%ExprInt;)+>
<!ATTLIST IDSArrayExprIndex 
           name CDATA #IMPLIED>

<!-- affectation -->
<!-- indice et valeur -->
<!ELEMENT IDSJavaArrayAssignmentStatment (%ExprInt;,%ExprInt;)+>
<!ATTLIST IDSJavaArrayAssignmentStatment 
           name CDATA #IMPLIED>

<!-- JML sur les tableaux -->

<!-- for all -->
<!-- la variable entière d'index, la condition à vérifier pour la variable d'index, -->
<!-- la condition à vérifier -->
<!ELEMENT IDSJMLForAll (IDSExprIdent,%ExprLogical;,%ExprLogical;)+>


<!-- exist -->
<!-- la variable entière d'index,  la condition à vérifier par la variable d'index, -->
<!-- la condition à vérifier -->
<!ELEMENT IDSJMLExist (IDSExprIdent,%ExprLogical;,%ExprLogical;)+>



<!-- if -->
<!ELEMENT IDSJavaIfStatment (cond,if,else?)>
<!ELEMENT cond (%ExprLogical;)>
<!ELEMENT if (%javaBloc;)>
<!ELEMENT else (%javaBloc;)>


<!-- while -->
<!ELEMENT IDSJavaWhileStatment (whileCond,whileBloc)>
<!ATTLIST IDSJavaWhileStatment ident CDATA #IMPLIED>

<!ELEMENT whileCond (%ExprLogical;)>
<!ELEMENT whileBloc (%javaBloc;)>

<!-- return -->
<!ELEMENT IDSJavaReturnStatment (%ExprInt;)>

=== mdbekkouche/LocFaults-IISs/core/xml/search.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/css" href="method.css"?>
<!DOCTYPE method SYSTEM "method.dtd">

<!--  exemple du linear search      -->

<!-- entete -->
<method>

<methodComment>
     exemple du search
</methodComment>
    
  <IDSMethod>
    <IDSSignature returnType="int" name="linearSearch">
    <IDSParameter type="int">
      <IDSArrayExprIdent name="tab" length="256"/>
    </IDSParameter>
    <IDSParameter type="int">
      <IDSExprIdent name="x"/>
    </IDSParameter>
    </IDSSignature>

    <!-- specification -->
    <IDSMethodSpecification>
      <IDSEnsuresClause> 
	<IDSExprLogicalAnd>
	  <IDSExprJMLImplies>
	    <IDSExprEquality>
              <IDSExprJMLResult/>
	      <IDSExprDecimalIntegerLiteral value="-1" />
	    </IDSExprEquality>
	    <IDSJMLForAll>
	      <IDSExprIdent name="i"/>
	      <IDSExprLogicalAnd>
		<IDSExprSupEqual>
		  <IDSExprIdent name="i"/>
		  <IDSExprDecimalIntegerLiteral value="0" />
		</IDSExprSupEqual>
		<IDSExprInf>
		  <IDSExprIdent name="i"/>
		  <LengthIdent name="tab" length="256"/>
		</IDSExprInf>
	      </IDSExprLogicalAnd>
	      <IDSExprLogicalNot>
		<IDSExprEquality>
		  <IDSArrayExprIndex name="tab">
		    <IDSExprIdent name="i"/>
		  </IDSArrayExprIndex>
         	  <IDSExprIdent name="x"/>
		</IDSExprEquality>
	      </IDSExprLogicalNot>
	    </IDSJMLForAll>
	  </IDSExprJMLImplies>
	  <IDSExprJMLImplies>
	    <IDSExprLogicalNot>
              <IDSExprEquality>
                 <IDSExprJMLResult/>
	         <IDSExprDecimalIntegerLiteral value="-1" />
	      </IDSExprEquality>
	    </IDSExprLogicalNot>
            <IDSExprEquality>
	      <IDSArrayExprIndex name="tab">
		    <IDSExprJMLResult/>
	      </IDSArrayExprIndex>
              <IDSExprIdent name="x"/>
	    </IDSExprEquality>
	  </IDSExprJMLImplies>
	</IDSExprLogicalAnd>
      </IDSEnsuresClause> 
  </IDSMethodSpecification>

  <!-- programme -->
  <IDSJavaBloc> 
  <IDSJavaDeclVarStatment name="result">
	<IDSExprDecimalIntegerLiteral value="-1" />
  </IDSJavaDeclVarStatment>
  <IDSJavaDeclVarStatment name="i">
	<IDSExprDecimalIntegerLiteral value="0" />
  </IDSJavaDeclVarStatment>
  <IDSJavaWhileStatment id="1">
     <whileCond>
        <IDSExprLogicalAnd>
	    <IDSExprInf>
            <IDSExprIdent name="i"/>
            <LengthIdent name="tab" length="256"/>
	</IDSExprInf>
	    <IDSExprEquality>
            <IDSExprIdent name="result"/>
            	<IDSExprDecimalIntegerLiteral value="-1" />
	</IDSExprEquality>
      </IDSExprLogicalAnd>
     </whileCond>
     <whileBloc>
        <IDSJavaBloc> 
           <IDSJavaIfStatment>
             <cond>
                <IDSExprEquality>
        	    <IDSArrayExprIndex name="tab">
                       <IDSExprIdent name="i"/>
        	    </IDSArrayExprIndex>
	            <IDSExprIdent name="x"/>
                </IDSExprEquality>
             </cond>
             <if>
	        <IDSJavaBloc> 
	            <IDSJavaAssignmentStatment name="result">
                        <IDSExprIdent name="i"/>
	            </IDSJavaAssignmentStatment>
	        </IDSJavaBloc> 
             </if>
          </IDSJavaIfStatment>
          <IDSJavaAssignmentStatment name="i">
	       <IDSExprPlus>
	          <IDSExprIdent name="i"/>
                  <IDSExprDecimalIntegerLiteral value="1" />
	        </IDSExprPlus>
	  </IDSJavaAssignmentStatment>
        </IDSJavaBloc> 
     </whileBloc>
  </IDSJavaWhileStatment>
  <IDSJavaReturnStatment>
    <IDSExprIdent name="result"/>
  </IDSJavaReturnStatment>
  </IDSJavaBloc> 
</IDSMethod>
</method>

=== mdbekkouche/LocFaults-IISs/core/xml/SquareSumI.xml
<?xml version="1.0" ?>
 <?xml-stylesheet type="text/css" href="method.css"?> 
 <!DOCTYPE method SYSTEM "method.dtd">
<method>
  <IDSMethod>
    <IDSSignature returnType="int" name="somme">
    <IDSParameter type="int">
      <IDSExprIdent name="n"/>
    </IDSParameter>
     <IDSParameter type="int">
      <IDSExprIdent name="p"/>
    </IDSParameter>
 </IDSSignature>
  
<IDSMethodSpecification>
<IDSRequiresClause>
<IDSExprLogicalAnd>

<IDSExprLogicalAnd>

<IDSExprSupEqual>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>

<IDSExprSupEqual>
<IDSExprIdent name="p"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>
</IDSExprLogicalAnd>

<IDSExprInfEqual>
<IDSExprIdent name="p"/>
<IDSExprIdent name="n"/>
</IDSExprInfEqual>


</IDSExprLogicalAnd>


</IDSRequiresClause>
<IDSEnsuresClause>
<IDSExprEquality>
<IDSExprJMLResult />

<IDSExprMinus>

<IDSExprDiv>
<IDSExprTimes>
<IDSExprTimes>
<IDSExprIdent name="n"/>
<IDSExprPlus>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSExprTimes>
<IDSExprPlus>
<IDSExprTimes>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="2"/>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="6"/>
</IDSExprDiv>

<IDSExprDiv>
<IDSExprTimes>
<IDSExprTimes>
<IDSExprMinus>
  <IDSExprIdent name="p"/>
  <IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprMinus>


<IDSExprIdent name="p"/>

</IDSExprTimes>
<IDSExprPlus>
<IDSExprTimes>
<IDSExprMinus>
  <IDSExprIdent name="p"/>
  <IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprMinus>

<IDSExprDecimalIntegerLiteral value="2"/>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="6"/>
</IDSExprDiv>
</IDSExprMinus>

</IDSExprEquality>
</IDSEnsuresClause>
</IDSMethodSpecification>
  <!-- le code de la methode -->
    <IDSJavaBloc>
      <IDSJavaDeclVarStatment name="i" id="1">
    </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="s" id="2">
      <IDSExprDecimalIntegerLiteral value="0"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaAssignmentStatment name="i" id="4">
         <IDSExprIdent name="p"/>
      </IDSJavaAssignmentStatment>

      <IDSJavaWhileStatment id="3">
        <whileCond>
          <IDSExprInfEqual>
          <IDSExprIdent name="i"/>
          <IDSExprIdent name="n"/>
          </IDSExprInfEqual>
        </whileCond>
          <whileBloc>
            <IDSJavaBloc>
              <IDSJavaAssignmentStatment name="s" id="4">
                <IDSExprPlus>
                <IDSExprIdent name="s"/>
                  <IDSExprTimes>
                  <IDSExprIdent name="i"/>
                  <IDSExprIdent name="i"/>
                  </IDSExprTimes>
                  </IDSExprPlus>
                </IDSJavaAssignmentStatment>
                  <IDSJavaAssignmentStatment name="i" id="5">
                    <IDSExprPlus>
                    <IDSExprIdent name="i"/>
                    <IDSExprDecimalIntegerLiteral value="1"/>
                    </IDSExprPlus>
                  </IDSJavaAssignmentStatment>
                </IDSJavaBloc>
              </whileBloc>
            </IDSJavaWhileStatment>
              <IDSJavaReturnStatment id="6">
              <IDSExprIdent name="s"/>
            </IDSJavaReturnStatment>
          </IDSJavaBloc>
        </IDSMethod>
        </method>

=== mdbekkouche/LocFaults-IISs/core/xml/SommeNPKO.xml
<?xml version="1.0" ?>
 <?xml-stylesheet type="text/css" href="method.css"?> 
 <!DOCTYPE method SYSTEM "method.dtd">
<method>
  <IDSMethod>
    <IDSSignature returnType="int" name="somme">
    <IDSParameter type="int">
      <IDSExprIdent name="n"/>
    </IDSParameter>
    <IDSParameter type="int">
      <IDSExprIdent name="p"/>
    </IDSParameter>
  </IDSSignature>
  
<IDSMethodSpecification>
<IDSRequiresClause>
<IDSExprLogicalAnd>
<IDSExprSupEqual>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>
<IDSExprSupEqual>
<IDSExprIdent name="p"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>
</IDSExprLogicalAnd>
</IDSRequiresClause>
<IDSEnsuresClause>
<IDSExprEquality>
<IDSExprJMLResult />
<IDSExprMinus>
<IDSExprDiv>
<IDSExprTimes>
<IDSExprIdent name="n"/>
<IDSExprPlus>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="2"/>
</IDSExprDiv>
<IDSExprDiv>
<IDSExprTimes>
<IDSExprMinus>
<IDSExprIdent name="p"/>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprMinus>
<IDSExprIdent name="p"/>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="2"/>
</IDSExprDiv>
</IDSExprMinus>
</IDSExprEquality>
</IDSEnsuresClause>
</IDSMethodSpecification>
  <!-- le code de la methode -->
    <IDSJavaBloc>
      <IDSJavaDeclVarStatment name="s" id="1">
      <IDSExprDecimalIntegerLiteral value="0"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="i" id="2">
      <IDSExprDecimalIntegerLiteral value="0"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaAssignmentStatment name="i" id="3">
      <IDSExprIdent name="p"/>
    </IDSJavaAssignmentStatment>
      <IDSJavaWhileStatment id="4">
        <whileCond>
          <IDSExprInfEqual>
          <IDSExprIdent name="i"/>
          <IDSExprIdent name="n"/>
          </IDSExprInfEqual>
        </whileCond>
          <whileBloc>
            <IDSJavaBloc>
              <IDSJavaAssignmentStatment name="s" id="5">
                <IDSExprPlus>
                <IDSExprIdent name="s"/>
                <IDSExprIdent name="i"/>
                </IDSExprPlus>
              </IDSJavaAssignmentStatment>
                <IDSJavaAssignmentStatment name="i" id="6">
                  <IDSExprPlus>
                  <IDSExprIdent name="i"/>
                  <IDSExprDecimalIntegerLiteral value="1"/>
                  </IDSExprPlus>
                </IDSJavaAssignmentStatment>
              </IDSJavaBloc>
            </whileBloc>
          </IDSJavaWhileStatment>
            <IDSJavaReturnStatment id="7">
            <IDSExprIdent name="s"/>
          </IDSJavaReturnStatment>
        </IDSJavaBloc>
      </IDSMethod>
      </method>

=== mdbekkouche/LocFaults-IISs/core/xml/SquareSum.xml
<?xml version="1.0" ?>
 <?xml-stylesheet type="text/css" href="method.css"?> 
 <!DOCTYPE method SYSTEM "method.dtd">
<method>
  <IDSMethod>
    <IDSSignature returnType="int" name="somme">
    <IDSParameter type="int">
      <IDSExprIdent name="n"/>
    </IDSParameter>
  </IDSSignature>
  
<IDSMethodSpecification>
<IDSRequiresClause>
<IDSExprSupEqual>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>
</IDSRequiresClause>
<IDSEnsuresClause>
<IDSExprEquality>
<IDSExprJMLResult />
<IDSExprDiv>
<IDSExprTimes>
<IDSExprTimes>
<IDSExprIdent name="n"/>
<IDSExprPlus>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSExprTimes>
<IDSExprPlus>
<IDSExprTimes>
<IDSExprIdent name="n"/>
<IDSExprDecimalIntegerLiteral value="2"/>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSExprTimes>
<IDSExprDecimalIntegerLiteral value="6"/>
</IDSExprDiv>
</IDSExprEquality>
</IDSEnsuresClause>
</IDSMethodSpecification>
  <!-- le code de la methode -->
    <IDSJavaBloc>
      <IDSJavaDeclVarStatment name="i" id="1">
    </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="s" id="2">
      <IDSExprDecimalIntegerLiteral value="0"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaWhileStatment id="3">
        <whileCond>
          <IDSExprInfEqual>
          <IDSExprIdent name="i"/>
          <IDSExprIdent name="n"/>
          </IDSExprInfEqual>
        </whileCond>
          <whileBloc>
            <IDSJavaBloc>
              <IDSJavaAssignmentStatment name="s" id="4">
                <IDSExprPlus>
                <IDSExprIdent name="s"/>
                  <IDSExprTimes>
                  <IDSExprIdent name="i"/>
                  <IDSExprIdent name="i"/>
                  </IDSExprTimes>
                  </IDSExprPlus>
                </IDSJavaAssignmentStatment>
                  <IDSJavaAssignmentStatment name="i" id="5">
                    <IDSExprPlus>
                    <IDSExprIdent name="i"/>
                    <IDSExprDecimalIntegerLiteral value="1"/>
                    </IDSExprPlus>
                  </IDSJavaAssignmentStatment>
                </IDSJavaBloc>
              </whileBloc>
            </IDSJavaWhileStatment>
              <IDSJavaReturnStatment id="6">
              <IDSExprIdent name="s"/>
            </IDSJavaReturnStatment>
          </IDSJavaBloc>
        </IDSMethod>
        </method>
