=== mdbekkouche/LocFaults-IISs/core/xml/method.dtd
<!-- IDS d'une methode -->
<!-- ***************** -->

<!-- Tous les elements qui commencent par IDS sont dans l'IDS du projet java
     les modifications par rapport au projet java sont indiquees en commentaire -->


<!-- la syntaxe des expressions -->

<!-- les expressions entieres -->
<!-- j'ai enleve expr a la fin : IDSExprPlusEpr devient IDSExprPlus -->
<!ENTITY % ExprInt "(IDSExprIdent|IDSArrayExprIndex|LengthIdent|IDSExprPlus|IDSExprMinus|IDSExprTimes|IDSExprDecimalIntegerLiteral|IDSExprParenthesis|IDSExprJMLResult)">

<!ELEMENT IDSExprPlus (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprMinus (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprTimes (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprDiv (%ExprInt;,(%ExprInt;)+)>
<!ELEMENT IDSExprDecimalIntegerLiteral EMPTY>
<!ATTLIST IDSExprDecimalIntegerLiteral value CDATA #IMPLIED>
<!-- ******** -->

<!-- les expressions logiques -->
<!-- j'ai rajoute ExprLogical en racine de toutes les expressions logiques -->
<!-- j'ai enleve expr a la fin : IDSExprLogicalOrEpr devient IDSExprLogicalOr -->
<!ENTITY % ExprLogical "(IDSExprLogicalOr|IDSExprLogicalAnd|IDSExprLogicalNot|IDSExprParenthesis|IDSExprEquality|IDSExprSup|IDSExprInf|IDSExprJMLimplies|IDSJMLForAll|IDSJMLExist|IDSJMLAssert|IDSJMLAlldiff)">

<!ELEMENT IDSExprLogicalOr (%ExprLogical;,(%ExprLogical;)+)>
<!ELEMENT IDSExprLogicalAnd (%ExprLogical;,(%ExprLogical;)+)>
<!ELEMENT IDSExprLogicalNot (%ExprLogical;)>
<!ELEMENT IDSExprJMLimplies (%ExprLogical;,%ExprLogical;)>

<!-- couple d'expressions entieres pour les operations de comparaison -->
<!ENTITY % Compare "(%ExprInt;,%ExprInt;)">

<!-- operateurs de comparaison -->
<!ELEMENT IDSExprEquality (%Compare;)>
<!ELEMENT IDSExprSup (%Compare;)>
<!ELEMENT IDSExprInf (%Compare;)>
<!ELEMENT IDSExprSupEqual (%Compare;)>
<!ELEMENT IDSExprInfEqual (%Compare;)>

<!-- ******** -->

<!-- les parentheses -->
<!ELEMENT IDSExprParenthesis (%ExprLogical;|%ExprInt;)*>

<!-- **************************************************** -->
<!-- element racine : la methode -->

<!-- fichier a analyser -->
<!ELEMENT method (methodComment+,IDSMethod)>

<!ELEMENT methodComment (#PCDATA)>

<!-- signature, specification, program -->
<!ELEMENT IDSMethod (IDSSignature,IDSMethodSpecification,IDSJavaBloc)>

<!-- signature = parametres -->
<!ELEMENT IDSSignature (IDSParameter)>
<!ATTLIST IDSSignature returnType CDATA #IMPLIED
                    name CDATA #IMPLIED>


<!-- les parametres -->
<!ELEMENT IDSParameter (IDSExprIdent|IDSArrayExprIdent)>
<!ATTLIST IDSParameter type CDATA #IMPLIED>


<!-- la specification = requires optionnel et ensure obligatoire -->
<!ELEMENT IDSMethodSpecification (IDSRequiresClause+,IDSEnsuresClause)>

<!-- requires et ensures -->
<!ELEMENT IDSRequiresClause (%ExprLogical;)>
<!ELEMENT IDSEnsuresClause (%ExprLogical;)>

<!-- ASSERT -->
<!ELEMENT IDSJMLAssert (%ExprLogical;)>

<!-- ALLDIFF -->
<!ELEMENT IDSJMLAlldiff (IDSArrayExprIdent)>


<!-- le \result de la specification -->
<!-- dans jmlTT, IDSExprB_Result avec attribut name="" -->
<!ELEMENT IDSExprJMLResult EMPTY>


<!-- **************************************************** -->

<!-- un bloc java : declaration de variables, affectation, if, while -->
<!ENTITY % javaBloc "(IDSJavaDeclVarStatment*,(IDSJavaAssignmentStatment*|IDSJavaIfStatment*|IDSJavaWhileStatment*))">

<!-- le programme = un bloc java suivi eventuellement de return -->
<!ELEMENT IDSJavaBloc (%javaBloc;,IDSJavaReturnStatment?)>

<!-- variables simples -->

<!-- declaration -->
<!ELEMENT IDSJavaDeclVarStatment (%ExprInt;)>
<!ATTLIST IDSJavaDeclVarStatment name CDATA #IMPLIED>

<!-- les identificateurs -->
<!-- A CHANGER : name = nom dans projet SI2 -->
<!ELEMENT IDSExprIdent EMPTY>
<!ATTLIST IDSExprIdent name CDATA #IMPLIED> 

<!-- affectation -->
<!ELEMENT IDSJavaAssignmentStatment (%ExprInt;)+>
<!ATTLIST IDSJavaAssignmentStatment name CDATA #IMPLIED>

<!-- les tableaux -->


<!-- variable pour représenter la longueur du tableau -->
<!--  name  est le nom du tableau associé, -->
<!--  la longueur se trouve dans la var tableau elle-même  -->
<!ELEMENT LengthIdent EMPTY>
<!ATTLIST  LengthIdent
           name CDATA #IMPLIED>

<!-- declaration -->
<!ELEMENT IDSJavaDeclArrayStatment EMPTY>
<!ATTLIST IDSJavaDeclArrayStatment 
          length CDATA #IMPLIED
          name CDATA #IMPLIED>

<!-- les identificateurs -->
<!ELEMENT IDSArrayExprIdent EMPTY>
<!ATTLIST IDSArrayExprIdent 
           length CDATA #IMPLIED
           name CDATA #IMPLIED>

<!-- les valeurs  -->
<!ELEMENT IDSArrayExprIndex (%ExprInt;)+>
<!ATTLIST IDSArrayExprIndex 
           name CDATA #IMPLIED>

<!-- affectation -->
<!-- indice et valeur -->
<!ELEMENT IDSJavaArrayAssignmentStatment (%ExprInt;,%ExprInt;)+>
<!ATTLIST IDSJavaArrayAssignmentStatment 
           name CDATA #IMPLIED>

<!-- JML sur les tableaux -->

<!-- for all -->
<!-- la variable entière d'index, la condition à vérifier pour la variable d'index, -->
<!-- la condition à vérifier -->
<!ELEMENT IDSJMLForAll (IDSExprIdent,%ExprLogical;,%ExprLogical;)+>


<!-- exist -->
<!-- la variable entière d'index,  la condition à vérifier par la variable d'index, -->
<!-- la condition à vérifier -->
<!ELEMENT IDSJMLExist (IDSExprIdent,%ExprLogical;,%ExprLogical;)+>



<!-- if -->
<!ELEMENT IDSJavaIfStatment (cond,if,else?)>
<!ELEMENT cond (%ExprLogical;)>
<!ELEMENT if (%javaBloc;)>
<!ELEMENT else (%javaBloc;)>


<!-- while -->
<!ELEMENT IDSJavaWhileStatment (whileCond,whileBloc)>
<!ATTLIST IDSJavaWhileStatment ident CDATA #IMPLIED>

<!ELEMENT whileCond (%ExprLogical;)>
<!ELEMENT whileBloc (%javaBloc;)>

<!-- return -->
<!ELEMENT IDSJavaReturnStatment (%ExprInt;)>

=== mdbekkouche/LocFaults-IISs/core/xml/sommeTabCarreOK.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/css" href="method.css"?>
<!DOCTYPE method SYSTEM "method.dtd">

<!--  SOMME DES carres des n premiers entiers qui sont dans tab    -->
                       
<!-- \ensures                          -->
<!--   \result == n*(n+1)*(2*n+1)/6            -->    
<!--                                   -->
<!-- int somme(tab) {                  --> 
<!--    int s = 0;                     -->
<!--    int i = 0;                     -->
<!--    while (i!=tab.length) {        -->     
<!--        s=s+tab[i]*tab[i]          -->
<!--        i+=i+1;                    -->
<!--    }                              -->
<!--    return s;                      -->
<!-- }                                 -->

<!-- entete -->
<method>

<methodComment>
     somme des carres des n premiers entiers contenus dans tab
</methodComment>
    
  <IDSMethod>

    <!-- signature -->
    <IDSSignature returnType="int" name="somme">
    <IDSParameter type="int">
      <IDSArrayExprIdent name="tab" length="5"/>
    </IDSParameter>
    <IDSParameter type="int">
      <IDSExprIdent name="n"/>
    </IDSParameter>
    </IDSSignature>

    <!-- specification -->

    <IDSMethodSpecification>

    <!-- requires -->
    <IDSRequiresClause> 


          <IDSJMLAllDiff>
                  <IDSArrayExprIdent name="tab" length="5"/>
           </IDSJMLAllDiff>


      </IDSRequiresClause>

    <!-- ensures  -->
      <IDSEnsuresClause> 
	 <IDSExprEquality>
            <IDSExprJMLResult/>
	    	<IDSExprDiv>
    	    	<IDSExprTimes>
		    <IDSExprIdent name="n"/>
        	      	<IDSExprTimes>
                             <IDSExprPlus>
	                	<IDSExprIdent name="n"/>
		                <IDSExprDecimalIntegerLiteral value="1"/>
	                     </IDSExprPlus>
                             <IDSExprPlus>
        	         	<IDSExprTimes>
	                	    <IDSExprIdent name="n"/>
		                    <IDSExprDecimalIntegerLiteral value="2"/>
                                </IDSExprTimes>
		                <IDSExprDecimalIntegerLiteral value="1"/>
	                     </IDSExprPlus>
                       </IDSExprTimes>
	        </IDSExprTimes>  
                <IDSExprDecimalIntegerLiteral value="6"/>
              </IDSExprDiv>
	</IDSExprEquality>
      </IDSEnsuresClause> 
   </IDSMethodSpecification>

  <!-- programme -->
  <IDSJavaBloc> 
      <IDSJavaDeclVarStatment name="i">
	<IDSExprDecimalIntegerLiteral value="0" />
      </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="s">
	<IDSExprDecimalIntegerLiteral value="0" />
      </IDSJavaDeclVarStatment>

     <IDSJMLAssert>
       <IDSExprLogicalAnd>
	 <IDSExprEquality>
	    <IDSExprIdent name="n"/>
              <IDSExprMinus>
                <LengthIdent name="tab" length="5"/>
		<IDSExprDecimalIntegerLiteral value="1"/>
              </IDSExprMinus>

	 </IDSExprEquality>

	<IDSJMLForAll>
	  <IDSExprIdent name="k"/>
	  <IDSExprLogicalAnd>
		<IDSExprSupEqual>
		  <IDSExprIdent name="k"/>
		  <IDSExprDecimalIntegerLiteral value="0" />
		</IDSExprSupEqual>
		<IDSExprInf>
		  <IDSExprIdent name="k"/>
 		  <LengthIdent name="tab" length="5"/>
	        </IDSExprInf>
           </IDSExprLogicalAnd>
	  <IDSExprLogicalAnd>
           <IDSExprSupEqual>
		  <IDSArrayExprIndex name="tab">
		    <IDSExprIdent name="k"/>
		  </IDSArrayExprIndex>
		  <IDSExprDecimalIntegerLiteral value="0" />
	  </IDSExprSupEqual>
           <IDSExprInf>
		  <IDSArrayExprIndex name="tab">
		    <IDSExprIdent name="k"/>
		  </IDSArrayExprIndex>
 		  <LengthIdent name="tab" length="5"/>
	  </IDSExprInf>
	  </IDSExprLogicalAnd>

	</IDSJMLForAll>
       </IDSExprLogicalAnd>

     </IDSJMLAssert>


      <IDSJavaWhileStatment id="1">
         <whileCond>
	    <IDSExprInf>
                 <IDSExprIdent name="i"/>
		  <LengthIdent name="tab" length="5"/>
	    </IDSExprInf>
         </whileCond>
         <whileBloc>
            <IDSJavaBloc> 
              	<IDSJavaAssignmentStatment name="s">
	            <IDSExprPlus>
	        	<IDSExprIdent name="s"/>
                        <IDSExprTimes>
		           <IDSArrayExprIndex name="tab">
		           <IDSExprIdent name="i"/>
		        </IDSArrayExprIndex>
		        <IDSArrayExprIndex name="tab">
		           <IDSExprIdent name="i"/>
		        </IDSArrayExprIndex>
                        </IDSExprTimes>
                    </IDSExprPlus>
	        </IDSJavaAssignmentStatment>
             	<IDSJavaAssignmentStatment name="i">
	            <IDSExprPlus>
	        	<IDSExprIdent name="i"/>
                        <IDSExprDecimalIntegerLiteral value="1" />
	           </IDSExprPlus>
	        </IDSJavaAssignmentStatment>
            </IDSJavaBloc> 
         </whileBloc>
      </IDSJavaWhileStatment>
  <IDSJavaReturnStatment>
    <IDSExprIdent name="s"/>
  </IDSJavaReturnStatment>
  </IDSJavaBloc> 
</IDSMethod>
</method>

=== mdbekkouche/LocFaults-IISs/core/xml/simple.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/css" href="method.css"?>
<!DOCTYPE method SYSTEM "method.dtd">

<!--  exemple simple avec if else imbrique et test sur variable intermediaire          -->
                       
<!-- \ensures                         -->
<!--   (i<j) ==> \result == 1 &&      -->    
<!--   !(i<j) ==> \result == 10000      --> 
<!--                                    -->
<!-- int simple(i,j) {                  --> 
<!--    int result;                     -->
<!--    int k=0;                          -->               
<!--    if (i<=j) k=k+1;                  -->                    
<!--    if (k==1 && i!=j) result = 1;                       -->
<!--            else result = 10000;                        -->                    
<!--    return result;                  -->
<!-- }                                        -->

<!-- entete -->
<method>

<methodComment>
     exemple simple style tritype
    </methodComment>
    
  <IDSMethod>
    <IDSSignature returnType="int" name="simple">
    <IDSParameter type="int">
      <IDSExprIdent name="i"/>
    </IDSParameter>
    <IDSParameter type="int">
      <IDSExprIdent name="j"/>
    </IDSParameter>
    </IDSSignature>

    <!-- specification -->
    <IDSMethodSpecification>
      <IDSEnsuresClause> 
         <IDSExprLogicalAnd>
	  <IDSExprJMLImplies>
		<IDSExprInf>
		   	<IDSExprIdent name="i" />		
                        <IDSExprIdent name="j" />
                </IDSExprInf>
	      <IDSExprEquality>
		<IDSExprJMLResult/>
		<IDSExprDecimalIntegerLiteral value="1" />
	      </IDSExprEquality>
	  </IDSExprJMLImplies>
	  <IDSExprJMLImplies>
		<IDSExprSupEqual>
		   	<IDSExprIdent name="i" />		
                        <IDSExprIdent name="j" />
                </IDSExprSupEqual>
	      <IDSExprEquality>
		<IDSExprJMLResult/>
		<IDSExprDecimalIntegerLiteral value="10" />
	      </IDSExprEquality>
	  </IDSExprJMLImplies>
	  </IDSExprLogicalAnd>
      </IDSEnsuresClause> 
  </IDSMethodSpecification>

  <!-- programme -->
  <IDSJavaBloc> 
  <IDSJavaDeclVarStatment name="result">
  </IDSJavaDeclVarStatment>
  <IDSJavaDeclVarStatment name="k">
	<IDSExprDecimalIntegerLiteral value="0" />
  </IDSJavaDeclVarStatment>

  <IDSJavaIfStatment>
    <cond>
      <IDSExprInfEqual>
	<IDSExprIdent name="i"/>
	<IDSExprIdent name="j"/>
      </IDSExprInfEqual>
    </cond>
    <if>
	  <IDSJavaBloc> 
	    <IDSJavaAssignmentStatment name="k">
	      	<IDSExprPlus>
		<IDSExprIdent name="k"/>
		<IDSExprDecimalIntegerLiteral value="1"/>
	      </IDSExprPlus>
	    </IDSJavaAssignmentStatment>
	    </IDSJavaBloc> 
    </if>
  </IDSJavaIfStatment>
  <IDSJavaIfStatment>
    <cond>
      <IDSExprLogicalAnd>
	<IDSExprEquality>
	   <IDSExprIdent name="k"/>
	   <IDSExprDecimalIntegerLiteral value="1"/>
        </IDSExprEquality>
      <IDSExprLogicalNot>
         <IDSExprEquality>
	    <IDSExprIdent name="i"/>
	    <IDSExprIdent name="j"/>
         </IDSExprEquality>
      </IDSExprLogicalNot>
      </IDSExprLogicalAnd>
    </cond>
    <if>
       <IDSJavaBloc> 
         <IDSJavaAssignmentStatment name="result">
	      <IDSExprDecimalIntegerLiteral value="1"/>
         </IDSJavaAssignmentStatment>
       </IDSJavaBloc> 
    </if>
      <else>
         <IDSJavaBloc>
	    <IDSJavaAssignmentStatment name="result">
	      <IDSExprDecimalIntegerLiteral value="10"/>
         </IDSJavaAssignmentStatment>
       </IDSJavaBloc> 
    </else>
  </IDSJavaIfStatment>
  <IDSJavaReturnStatment>
    <IDSExprIdent name="result"/>
  </IDSJavaReturnStatment>
  </IDSJavaBloc>
  </IDSMethod>
</method>

=== mdbekkouche/LocFaults-IISs/core/xml/BsearchKO.xml
<?xml version="1.0" ?>
 <?xml-stylesheet type="text/css" href="method.css"?> 
 <!DOCTYPE method SYSTEM "method.dtd">
<method>
  <IDSMethod>
    <IDSSignature returnType="int" name="binarySearch">
    <IDSParameter type="int">
      <IDSArrayExprIdent name="tab" length="8" />
    </IDSParameter>
    <IDSParameter type="int">
      <IDSExprIdent name="x"/>
    </IDSParameter>
  </IDSSignature>
  
<IDSMethodSpecification>
<IDSRequiresClause>
<IDSJMLForAll>
<IDSExprIdent name="i" />
<IDSExprLogicalAnd>
<IDSExprSupEqual>
<IDSExprIdent name="i"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>
<IDSExprInf>
<IDSExprIdent name="i"/>
<IDSExprMinus>
<LengthIdent name="tab" length="8" />
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprMinus>
</IDSExprInf>
</IDSExprLogicalAnd>
<IDSExprInfEqual>
<IDSArrayExprIndex name="tab">
<IDSExprIdent name="i"/>
</IDSArrayExprIndex>
<IDSArrayExprIndex name="tab">
<IDSExprPlus>
<IDSExprIdent name="i"/>
<IDSExprDecimalIntegerLiteral value="1"/>
</IDSExprPlus>
</IDSArrayExprIndex>
</IDSExprInfEqual>
</IDSJMLForAll>
</IDSRequiresClause>
<IDSEnsuresClause>
<IDSExprLogicalAnd>
<IDSExprJMLImplies>
<IDSExprEquality>
<IDSExprJMLResult />
<IDSExprDecimalIntegerLiteral value="-1"/>
</IDSExprEquality>
<IDSJMLForAll>
<IDSExprIdent name="i" />
<IDSExprLogicalAnd>
<IDSExprSupEqual>
<IDSExprIdent name="i"/>
<IDSExprDecimalIntegerLiteral value="0"/>
</IDSExprSupEqual>
<IDSExprInf>
<IDSExprIdent name="i"/>
<LengthIdent name="tab" length="8" />
</IDSExprInf>
</IDSExprLogicalAnd>
<IDSExprLogicalNot>
<IDSExprEquality>
<IDSArrayExprIndex name="tab">
<IDSExprIdent name="i"/>
</IDSArrayExprIndex>
<IDSExprIdent name="x"/>
</IDSExprEquality>
</IDSExprLogicalNot>
</IDSJMLForAll>
</IDSExprJMLImplies>
<IDSExprJMLImplies>
<IDSExprLogicalNot>
<IDSExprEquality>
<IDSExprJMLResult />
<IDSExprDecimalIntegerLiteral value="-1"/>
</IDSExprEquality>
</IDSExprLogicalNot>
<IDSExprEquality>
<IDSArrayExprIndex name="tab">
<IDSExprJMLResult />
</IDSArrayExprIndex>
<IDSExprIdent name="x"/>
</IDSExprEquality>
</IDSExprJMLImplies>
</IDSExprLogicalAnd>
</IDSEnsuresClause>
</IDSMethodSpecification>
  <!-- le code de la methode -->
    <IDSJavaBloc>
      <IDSJavaDeclVarStatment name="result" id="1">
      <IDSExprDecimalIntegerLiteral value="-1"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="milieu" id="2">
      <IDSExprDecimalIntegerLiteral value="0"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="gauche" id="3">
      <IDSExprDecimalIntegerLiteral value="0"/>
    </IDSJavaDeclVarStatment>
      <IDSJavaDeclVarStatment name="droite" id="4">
        <IDSExprMinus>
          <LengthIdent name="tab" length="8" />
          <IDSExprDecimalIntegerLiteral value="1"/>
          </IDSExprMinus>
        </IDSJavaDeclVarStatment>
          <IDSJavaWhileStatment id="5">
            <whileCond>
              <IDSExprLogicalAnd>
                <IDSExprEquality>
                <IDSExprIdent name="result"/>
                <IDSExprDecimalIntegerLiteral value="-1"/>
                </IDSExprEquality>
                  <IDSExprInfEqual>
                  <IDSExprIdent name="gauche"/>
                  <IDSExprIdent name="droite"/>
                  </IDSExprInfEqual>
                  </IDSExprLogicalAnd>
                </whileCond>
                  <whileBloc>
                    <IDSJavaBloc>
                      <IDSJavaAssignmentStatment name="milieu" id="6">
                        <IDSExprDiv>
                          <IDSExprPlus>
                          <IDSExprIdent name="gauche"/>
                          <IDSExprIdent name="droite"/>
                          </IDSExprPlus>
                          <IDSExprDecimalIntegerLiteral value="2"/>
                          </IDSExprDiv>
                        </IDSJavaAssignmentStatment>
                          <IDSJavaIfStatment id="7">
                            <cond>
                              <IDSExprEquality>
                              <IDSArrayExprIndex name="tab">
                              <IDSExprIdent name="milieu"/>
                              </IDSArrayExprIndex>
                              <IDSExprIdent name="x"/>
                              </IDSExprEquality>
                            </cond>
                            <if>
                              <IDSJavaBloc>
                                <IDSJavaAssignmentStatment name="result" id="9">
                                <IDSExprIdent name="milieu"/>
                              </IDSJavaAssignmentStatment>
                            </IDSJavaBloc>
                            </if>
                            <else>
                              <IDSJavaBloc>
                                <IDSJavaIfStatment id="9">
                                  <cond>
                                    <IDSExprSup>
                                    <IDSArrayExprIndex name="tab">
                                    <IDSExprIdent name="milieu"/>
                                    </IDSArrayExprIndex>
                                    <IDSExprIdent name="x"/>
                                    </IDSExprSup>
                                  </cond>
                                  <if>
                                    <IDSJavaBloc>
                                      <IDSJavaAssignmentStatment name="droite" id="10">
                                        <IDSExprMinus>
                                        <IDSExprIdent name="milieu"/>
                                        <IDSExprDecimalIntegerLiteral value="1"/>
                                        </IDSExprMinus>
                                      </IDSJavaAssignmentStatment>
                                    </IDSJavaBloc>
                                    </if>
                                    <else>
                                      <IDSJavaBloc>
                                        <IDSJavaAssignmentStatment name="droite" id="11">
                                          <IDSExprMinus>
                                          <IDSExprIdent name="milieu"/>
                                          <IDSExprDecimalIntegerLiteral value="1"/>
                                          </IDSExprMinus>
                                        </IDSJavaAssignmentStatment>
                                      </IDSJavaBloc>
                                      </else>
                                    </IDSJavaIfStatment>
                                  </IDSJavaBloc>
                                  </else>
                                </IDSJavaIfStatment>
                              </IDSJavaBloc>
                            </whileBloc>
                          </IDSJavaWhileStatment>
                            <IDSJavaReturnStatment id="12">
                            <IDSExprIdent name="result"/>
                          </IDSJavaReturnStatment>
                        </IDSJavaBloc>
                      </IDSMethod>
                      </method>

=== mdbekkouche/LocFaults-IISs/core/xml/BubleSortMantovani.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/css" href="method.css"?>
<!DOCTYPE method SYSTEM "method.dtd">

<!--  exemple du tri a bulle -->

<!-- entete -->
<method>

<methodComment>
    buble sort 
</methodComment>
    
  <IDSMethod>
    <IDSSignature returnType="void" name="bubleSort">
    <IDSParameter type="int">
      <IDSArrayExprIdent name="t" length="16"/>
    </IDSParameter>
    </IDSSignature>

    <!-- specification -->
    <IDSMethodSpecification>

    <!-- require -->
    <IDSRequiresClause> 
	<IDSJMLForAll>
	  <IDSExprIdent name="i"/>
	  <IDSExprLogicalAnd>
		<IDSExprSupEqual>
		  <IDSExprIdent name="i"/>
		  <IDSExprDecimalIntegerLiteral value="0" />
		</IDSExprSupEqual>
		<IDSExprInf>
		  <IDSExprIdent name="i"/>
		         <LengthIdent name="t" length="16"/>
		</IDSExprInf>
           </IDSExprLogicalAnd>
            <IDSExprEquality>
		  <IDSArrayExprIndex name="t">
		    <IDSExprIdent name="i"/>
		  </IDSArrayExprIndex>
         	      <IDSExprMinus>
	       	      <IDSExprMinus>
         	         <LengthIdent name="t" length="16"/>
                          <IDSExprDecimalIntegerLiteral value="1" />
        	      </IDSExprMinus>
	         <IDSExprIdent name="i"/>
                     </IDSExprMinus>
	  </IDSExprEquality>
	</IDSJMLForAll>
      </IDSRequiresClause>

    <!-- ensures -->
      <IDSEnsuresClause> 
	<IDSJMLForAll>
	  <IDSExprIdent name="i"/>
	  <IDSExprLogicalAnd>
		<IDSExprSupEqual>
		  <IDSExprIdent name="i"/>
		  <IDSExprDecimalIntegerLiteral value="0" />
		</IDSExprSupEqual>
		<IDSExprInf>
		  <IDSExprIdent name="i"/>
         	      <IDSExprMinus>
		         <LengthIdent name="t" length="16"/>
		         <IDSExprDecimalIntegerLiteral value="1" />
	              </IDSExprMinus>
		</IDSExprInf>
           </IDSExprLogicalAnd>
           <IDSExprInfEqual>
		  <IDSArrayExprIndex name="t">
		    <IDSExprIdent name="i"/>
		  </IDSArrayExprIndex>
		  <IDSArrayExprIndex name="t">
         	      <IDSExprPlus>
		         <IDSExprIdent name="i"/>
		         <IDSExprDecimalIntegerLiteral value="1" />
        	      </IDSExprPlus>
		  </IDSArrayExprIndex>
	  </IDSExprInfEqual>
	</IDSJMLForAll>
      </IDSEnsuresClause> 
   </IDSMethodSpecification>

  <!-- programme -->
  <IDSJavaBloc>
     <IDSJavaDeclVarStatment name="i">
	<IDSExprDecimalIntegerLiteral value="0" />
   </IDSJavaDeclVarStatment>

   <IDSJavaDeclVarStatment name="j">
	<IDSExprDecimalIntegerLiteral value="0" />
   </IDSJavaDeclVarStatment>
          
    <IDSJavaDeclVarStatment name="aux">
          <IDSExprDecimalIntegerLiteral value="0" />
    </IDSJavaDeclVarStatment>


   <IDSJavaWhileStatment id="1">
     <whileCond>
        <IDSExprInf>
            <IDSExprIdent name="j"/>
            <LengthIdent name="t" length="16"/>
	</IDSExprInf>
     </whileCond>

     <whileBloc>
   
         <IDSJavaBloc>
           <IDSJavaAssignmentStatment name="i">
                   <IDSExprDecimalIntegerLiteral value="0" />
          </IDSJavaAssignmentStatment>

         <IDSJavaWhileStatment id="2">
             <whileCond>
                 <IDSExprInf>
                    <IDSExprIdent name="i"/>
		  <IDSExprMinus>
                    <LengthIdent name="t" length="16"/>
                    <IDSExprDecimalIntegerLiteral value="1" />
		  </IDSExprMinus>

	     </IDSExprInf>
             </whileCond>
             <whileBloc>
                <IDSJavaBloc> 
                  <IDSJavaIfStatment>
                    <cond>
                       <IDSExprSup>
        	         <IDSArrayExprIndex name="t">
                            <IDSExprIdent name="i"/>
        	         </IDSArrayExprIndex>
        	         <IDSArrayExprIndex name="t">
                            <IDSExprPlus>
                               <IDSExprIdent name="i"/>
                                <IDSExprDecimalIntegerLiteral value="1" />
                             </IDSExprPlus>
        	         </IDSArrayExprIndex>	                 
                       </IDSExprSup>
                    </cond>
                    <if>
                <IDSJavaBloc> 
        <IDSJavaAssignmentStatment name="aux">
             <IDSArrayExprIndex name="t">
                 <IDSExprIdent name="i"/>
             </IDSArrayExprIndex>
	</IDSJavaAssignmentStatment>

        <IDSJavaArrayAssignmentStatment name="t">
 	     <IDSExprIdent name="i"/>
             <IDSArrayExprIndex name="t">
                   <IDSExprPlus>
                      <IDSExprIdent name="i"/>
                      <IDSExprDecimalIntegerLiteral value="1" />
              </IDSExprPlus>
             </IDSArrayExprIndex>
        </IDSJavaArrayAssignmentStatment>

        <IDSJavaArrayAssignmentStatment name="t">
                   <IDSExprPlus>
                      <IDSExprIdent name="i"/>
                      <IDSExprDecimalIntegerLiteral value="1" />
              </IDSExprPlus>
               <IDSExprIdent name="aux"/>
         </IDSJavaArrayAssignmentStatment>

                </IDSJavaBloc> 
                    </if>
                 </IDSJavaIfStatment>

	  <IDSJavaAssignmentStatment name="i">
              <IDSExprPlus>
                  <IDSExprIdent name="i"/>
                  <IDSExprDecimalIntegerLiteral value="1" />
              </IDSExprPlus>
	  </IDSJavaAssignmentStatment>

              </IDSJavaBloc> 
           </whileBloc>
        </IDSJavaWhileStatment>



	  <IDSJavaAssignmentStatment name="j">
              <IDSExprPlus>
                  <IDSExprIdent name="j"/>
                  <IDSExprDecimalIntegerLiteral value="1" />
              </IDSExprPlus>
	  </IDSJavaAssignmentStatment>
  
     </IDSJavaBloc> 
   </whileBloc>
 </IDSJavaWhileStatment>
  <IDSJavaReturnStatment>
  </IDSJavaReturnStatment>
  </IDSJavaBloc> 
</IDSMethod>
</method>
